CREATE TABLE user_sessions (
    id CHAR(36) CHARACTER SET utf8 NOT NULL PRIMARY KEY COMMENT 'UUID',
    user_id CHAR(36) CHARACTER SET UTF8 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
